#!/bin/bash
cd "$(dirname "$0")/.." || exit 111

if [[ ! $(which yarn) ]]; then
  echo 'Install yarnpkg.com or use npm install instead of this script'
  exit 111
fi

yarn --prefer-offline || exit 111
