#!/bin/bash
cd "$(dirname "$0")/.." || exit 111

if [[ ! $(which yarn) ]]; then
  echo 'Install https://yarnpkg.com or use "npm install" instead of this script'
  exit 111
fi

# Install homebrew packages if running on macOS
if [[ -f "Brewfile" ]] && [[ "$(uname -s)" = "Darwin" ]]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "Installing Homebrew dependencies"
    brew bundle || exit 111
  }
fi

yarn --prefer-offline || exit 111
