#!/bin/bash
cd "$(dirname "$0")/.." || exit 111

kill "$(< ./.pidfile)" || {
  echo "Problem killing process. Remove the pidfile"
  exit 111
}

if [[ $(which brew) ]]; then
  brew services stop redis
fi

rm ./.pidfile
